# Preface {.unnumbered}

## RULES OF THE LABORATORY

Laboratory sessions are 2 hours long. The student is expected to spend all this time in the laboratory, either performing the experiment or writing the report. Students must work in pairs when taking measurements (the analysis should be done separately as a check). No coats or bags are allowed in the laboratory. No eating or drinking is allowed.

## LABORATORY REGISTERS

The laboratory register provides a record of each student's attendance and lists the experiments he/she has successfully completed. An 80% attendance is mandatory. If a student is absent due to illness a medical certificate must be submitted to the lecturer in charge. Students will be marked in on the attendance register when the experiment is complete and the equipment tidied.

## APPARATUS:

The apparatus will be found on the benches in the laboratory. Some items must be collected (and signed for) from the lecturer supervising the lab. These items must be returned when the experiment is complete and signed off.

If equipment is thought to be faulty consult the lecturer in charge. Apparatus should NEVER be moved from one bench to another. When the experiment is complete the equipment must be tidied/cleaned and left as it was found at the start.
